name: Build libwsc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libevent-dev \
            zlib1g-dev \
            libssl-dev

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIBWSC_USE_DEBUG=OFF

      - name: Build
        run: |
          cd build
          cmake --build .
